# Books table
booksTable:
  Type: AWS::DynamoDB::Table
  Properties: 
    AttributeDefinitions: 
      - AttributeName: "bookId"
        AttributeType: "S"
    BillingMode: PAY_PER_REQUEST
    KeySchema: 
      - AttributeName: "bookId"
        KeyType: "HASH"
    Tags: 
      - Key: Name
        Value: books-table

# Order table
orderTable:
  Type: AWS::DynamoDB::Table
  Properties: 
    AttributeDefinitions: 
      - AttributeName: "userId"
        AttributeType: "S"
      - AttributeName: "orderId"
        AttributeType: "S"
      - AttributeName: "bookId"
        AttributeType: "S"
      - AttributeName: "createdAt"
        AttributeType: "S"
    BillingMode: PAY_PER_REQUEST
    KeySchema: 
      - AttributeName: "userId"
        KeyType: "HASH"
      - AttributeName: "orderId"
        KeyType: "RANGE"
    GlobalSecondaryIndexes: 
      IndexName: "byOrder"
      KeySchema: 
        - AttributeName: "bookId"
          KeyType: "HASH"
        - AttributeName: "createdAt"
          KeyType: "RANGE"
      Projection: 
        ProjectionType: ALL
    Tags: 
      - Key: Name
        Value: order-table