service: serverless-appsync-backend

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: ap-northeast-1

plugins:
  - serverless-appsync-plugin

custom:
  appSync:
    name: youtubeAppSyncAPI
    authenticationType: AMAZON_COGNITO_USER_POOLS
    userPoolConfig:
      awsRegion: ap-northeast-1
      defaultAction: ALLOW
      userPoolId: !Ref cognitoUserPool
    mappingTemplatesLocation: mapping-templates
    mappingTemplates:
      - type: Query
        field: getBookById
        dataSource: booksTable
      - type: Mutation
        field: createBook
        dataSource: booksTable
    datasources:
      - type: AMAZON_DYNAMODB
        name: booksTable
        config:
          tableName: !Ref booksTable

resources:
  Resources:
    ${file(./resources.yml)}